name: Django CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      HOST_ADDRESS: ${{ secrets.HOST_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Export Files
      run: |
        echo $SSH_KEY > actions-poc.pem
        chmod 400 actions-poc.pem
        ssh -i "actions-poc.pem" $HOST_ADDRESS
        cd poc-actions
        echo "exporting files" > output.txt
        