name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/poc-actions
            git pull
            uv run manage.py migrate
            uv run manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx